title: Dayda
name: Office of Navajo and Hopi Indian Relocation
description: >-
  This is a catalog of datasets organized and made more accessible from the
  Office of Navajo and Hopi Indian Relocation, providing simple dowloadable CSV
  and JSON files, as well as Postman Collections you can use as part of
  workflows and other automation.
about: This is all about the entity.
source_url: 'http://example.com'
source_contact_type: general
source_phone: +1 555-555-5555
source_email: info@example.com
source_catalog: data.gov
profile_pic: >-
  https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Flag_of_the_Hopi_Reservation.svg/1200px-Flag_of_the_Hopi_Reservation.svg.png
favicon: /assets/img/favicon.png
url: 'http://office-of-navajo-and-hopi-indian-relocation.dayda.org'
encoding: utf-8
paginate: 25
paginate_path: '/page:num/'
markdown: kramdown
